### ISSUE TITLE
Rename Dyncss to Scss

### ISSUE THREAD

**Issue by DanielRuf** [typo3-themes/theme_bootstrap4#14]
The naming of the directory is currently not very clear. Why not just call it `Scss`?

**Comment by kaystrobach** [comment]
Think it’s because of the extension dyncss typically used in themes, but i think we should consider this

**Comment by DanielRuf** [comment]
Bump.

**Comment by kaystrobach** [comment]
Please provide a pull request, then it can be easily reviewed by the team. Thank you

**Comment by DanielRuf** [comment]
See https://github.com/typo3-themes/theme_bootstrap4/pull/65

**Comment by kaystrobach** [comment]
@tdeuling any objections?

**Comment by tdeuling** [comment]
Hmm, generally not. But we've a lot of existing Child-Themes that uses includes/import from that folder.
For one example: 
https://github.com/typo3-themes/theme_bootstrap4_child/blob/master/Resources/Private/Dyncss/import.scss

In case of renaming, we might need to modify them all. From that point I prefer to keep the name.

We'd called the folder Dyncss, because the Dyncss Extension handles the contained files. Dyncss isn't only used by Themes user - I've seen it often in non-themes-context.

BTW:
We're currently working on theme_bootstrap4:rebase, themes:8-0 and theme_bootstrap_child:master - I think we could push some new releases to TER soon.

**Comment by tdeuling** [comment]
A lot. All our projects are done by using themes. But it's ok. Just create a pull request with modified folder names.
